/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Request {
  payload:
    | UnsubscribeRequest
    | PingRequest
    | HeartbeatRequest
    | ServerHeartbeatRequest
    | AuthenticateRequest
    | LogoutRequest
    | SubscribeToDashboardRequest
    | SubscribeToDashboardsListRequest
    | FetchDashboardConfigRequest
    | FetchDashboardDraftRequest
    | CreateDashboardRequest
    | ImportDashboardRequest
    | UpdateDashboardRequest
    | UpdateDashboardDraftRequest
    | ResetDashboardDraftRequest
    | UpdateDashboardPermissionsRequest
    | UpdateDashboardShareSettingsRequest
    | DeleteDashboardRequest
    | SubscribeToUsersRequest
    | SubscribeToDashboardPermissionsRequest
    | FetchDashboardIdByLegacyIdRequest
    | RenameDashboardRequest;
  timestamp: string;
  traceId: string;
  correlationId: number;
}
export interface UnsubscribeRequest {
  type: "Unsubscribe";
}
export interface PingRequest {
  type: "Ping";
  simulateInternalError?: boolean;
  simulateTimeout?: boolean;
}
export interface HeartbeatRequest {
  type: "Heartbeat";
}
export interface ServerHeartbeatRequest {
  type: "ServerHeartbeat";
}
export interface AuthenticateRequest {
  type: "Authenticate";
  bearerToken: string;
}
export interface LogoutRequest {
  type: "Logout";
}
export interface SubscribeToDashboardRequest {
  type: "SubscribeToDashboard";
  id: string;
}
export interface SubscribeToDashboardsListRequest {
  type: "SubscribeToDashboardsList";
}
export interface FetchDashboardConfigRequest {
  type: "FetchDashboardConfig";
  id: string;
  digest?: string;
}
export interface FetchDashboardDraftRequest {
  type: "FetchDashboardDraft";
  id: string;
  digest?: string;
}
export interface CreateDashboardRequest {
  type: "CreateDashboard";
  name: string;
  config: string;
}
export interface ImportDashboardRequest {
  type: "ImportDashboard";
  name: string;
  config: string;
  permission: Permission;
  legacyId: number;
}
export interface UpdateDashboardRequest {
  type: "UpdateDashboard";
  id: string;
  name: string;
  config: string;
  status: Status;
  digest: string;
}
export interface UpdateDashboardDraftRequest {
  type: "UpdateDashboardDraft";
  id: string;
  config: string;
}
export interface ResetDashboardDraftRequest {
  type: "ResetDashboardDraft";
  id: string;
}
export interface UpdateDashboardPermissionsRequest {
  type: "UpdateDashboardPermissions";
  id: string;
  permissions: {
    user: string;
    permission: Permission;
  }[];
}
export interface UpdateDashboardShareSettingsRequest {
  type: "UpdateDashboardShareSettings";
  id: string;
  sharePermission: SharePermission;
}
export interface DeleteDashboardRequest {
  type: "DeleteDashboard";
  id: string;
}
export interface SubscribeToUsersRequest {
  type: "SubscribeToUsers";
}
export interface SubscribeToDashboardPermissionsRequest {
  type: "SubscribeToDashboardPermissions";
  id: string;
}
export interface FetchDashboardIdByLegacyIdRequest {
  type: "FetchDashboardIdByLegacyId";
  legacyId: number;
}
export interface RenameDashboardRequest {
  type: "RenameDashboard";
  id: string;
  name: string;
}

export const enum Permission {
  None = "None",
  Viewer = "Viewer",
  Editor = "Editor",
  Owner = "Owner"
}
export const enum Status {
  Active = "Active",
  Suspended = "Suspended",
  Archived = "Archived"
}
export const enum SharePermission {
  None = "None",
  Viewer = "Viewer",
  Editor = "Editor"
}
