export enum ETab {
    addTask = 'Add Task',
    activeTasks = 'Active Tasks',
    archivedTasks = 'Archived Tasks',
    instruments = 'Instruments',
    indicators = 'Indicators',
    productLogs = 'Product Logs',
    realAccounts = 'Real Accounts',
    virtualAccounts = 'Virtual Accounts',
    config = 'Config',
    wsRequest = 'WS Request',
    orderBook = 'Order Book',
    dashboards = 'Dashboards',
    tasks = 'Tasks',
    task = 'Task',
    runs = 'Runs',
    runsInfo = 'Runs Info',
    configs = 'Configs',
    statusMessages = 'Status Messages',
    activeOrders = 'Active Orders',
    addComponent = 'Add Component',
    state = 'State',
    balances = 'Balances',
    positions = 'Positions',
    robotPositions = 'Robot Positions',
    robotBalances = 'Robot Balances',
}
