export enum EAddTaskTabSelectors {
    AddTaskTab = 'addTaskTab',
    TaskTypeSelector = 'taskTypeSelector',
    BaseAssetSelector = 'baseAssetSelector',
    TotalAmountInput = 'amountInput',
    TotalAmountLabel = 'totalAmountLabel',
    ExchangeSelector = 'exchangeSelector',
    ExchangeBuySelector = '[data-test="buyInstrumentsForm"] [data-test="exchangeSelector"]',
    ExchangeSellSelector = '[data-test="sellInstrumentsForm"] [data-test="exchangeSelector"]',
    AccountSelector = 'accountSelector',
    InstrumentSelector = 'instrumentSelector',
    InstrumentLabel = 'instrumentLabel',
    InstrumentRoleSelector = 'instrumentRoleSelector',
    DeleteInstrumentButton = 'deleteInstrumentButton',
    SelectInstrumentButton = 'selectInstrumentButton',
    AddInstrumentButton = 'addInstrumentButton',
    OrderAmountInput = 'orderAmountInput',
    OrderAmountLabel = 'orderAmountLabel',
    CurrencyType = 'currencyType',
    MaxPremiumInput = 'maxPremiumInput',
    MaxPriceInput = 'maxPriceInput',
    MaxPriceLabel = 'maxPriceLabel',
    AggressionInput = 'aggressionInput',
    InstrumentAggressionInput = 'instrumentAggressionInput',
    AddTaskFormButton = 'addTaskFormButton',
    ResetFormButton = 'resetFormButton',
    BuyInstrumentsForm = 'buyInstrumentsForm',
    SellInstrumentsForm = 'sellInstrumentsForm',
    ResetPriceToCurrent = 'resetPriceToCurrent',
    TradingSwitch = 'tradingSwitch',
    WarningInstrumentIcon = '[data-test="instrumentSelector"] [aria-label="warning"]',
}
