/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type DashboardItem = DashboardsListItem & {
  draftDigest: string;
};

export interface Response {
  error?: ErrorResponse;
  payload?:
    | UnsubscribeResponse
    | PingResponse
    | HeartbeatResponse
    | AuthenticateResponse
    | LogoutResponse
    | SubscribeToDashboardResponse
    | SubscribeToDashboardsListResponse
    | FetchDashboardConfigResponse
    | FetchDashboardDraftResponse
    | CreateDashboardResponse
    | ImportDashboardResponse
    | UpdateDashboardResponse
    | UpdateDashboardDraftResponse
    | ResetDashboardDraftResponse
    | UpdateDashboardPermissionsResponse
    | UpdateDashboardShareSettingsResponse
    | DeleteDashboardResponse
    | SubscribeToUsersResponse
    | SubscribeToDashboardPermissionsResponse
    | FetchDashboardIdByLegacyIdResponse
    | RenameDashboardResponse;
  timestamp: string;
  traceId: string;
  correlationId: number;
  state: ResponseState;
}
export interface ErrorResponse {
  kind?: string;
  description: string;
  args?: {
    [k: string]: unknown;
  };
}
export interface UnsubscribeResponse {
  type: "Unsubscribed";
}
export interface PingResponse {
  type: "Pong";
}
export interface HeartbeatResponse {
  type: "Heartbeat";
}
export interface AuthenticateResponse {
  type: "Authenticated";
  username: string;
}
export interface LogoutResponse {
  type: "LoggedOut";
}
export interface SubscribeToDashboardResponse {
  type: "Dashboard";
  dashboard: DashboardItem;
}
export interface DashboardsListItem {
  id: string;
  name: string;
  kind: Kind;
  status: Status;
  digest?: string;
  insertionTime: string;
  hasDraft: boolean;
  sharePermission: SharePermission;
  permission: Permission;
  permissionsCount?: number;
  owners: User[];
}
export interface User {
  user: string;
}
export interface SubscribeToDashboardsListResponse {
  type: "DashboardsList";
  list: DashboardsListItem[];
}
export interface FetchDashboardConfigResponse {
  type: "DashboardConfig";
  config: string;
  digest: string;
}
export interface FetchDashboardDraftResponse {
  type: "DashboardDraft";
  draft: string;
  digest: string;
}
export interface CreateDashboardResponse {
  type: "DashboardCreated";
  id: string;
}
export interface ImportDashboardResponse {
  type: "DashboardImported";
  id: string;
}
export interface UpdateDashboardResponse {
  type: "DashboardUpdated";
}
export interface UpdateDashboardDraftResponse {
  type: "DashboardDraftUpdated";
}
export interface ResetDashboardDraftResponse {
  type: "DashboardDraftReset";
}
export interface UpdateDashboardPermissionsResponse {
  type: "PermissionsUpdated";
}
export interface UpdateDashboardShareSettingsResponse {
  type: "DashboardShareSettingsUpdated";
}
export interface DeleteDashboardResponse {
  type: "DashboardDeleted";
}
export interface SubscribeToUsersResponse {
  type: "UsersList";
  list: User[];
}
export interface SubscribeToDashboardPermissionsResponse {
  type: "DashboardPermissionsList";
  list: {
    user: string;
    permission: string;
  }[];
}
export interface FetchDashboardIdByLegacyIdResponse {
  type: "DashboardId";
  id: string;
}
export interface RenameDashboardResponse {
  type: "DashboardRenamed";
}

export const enum Kind {
  User = "User",
  Robot = "Robot"
}
export const enum Status {
  Active = "Active",
  Suspended = "Suspended",
  Archived = "Archived"
}
export const enum SharePermission {
  None = "None",
  Viewer = "Viewer",
  Editor = "Editor"
}
export const enum Permission {
  None = "None",
  Viewer = "Viewer",
  Editor = "Editor",
  Owner = "Owner"
}
export const enum ResponseState {
  Done = "Done",
  InProgress = "InProgress"
}
