const fs = require('fs');
const path = require('path');

function readFile(dir, fileName) {
    return new Promise((resolve, reject) => {
        fs.readFile(path.join(dir, fileName), 'utf8', (err, data) => {
            if (err) {
                reject(err);
                return;
            }

            resolve(data);
        });
    });
}

function writeFile(dir, fileName, data) {
    return new Promise((resolve, reject) => {
        fs.writeFile(path.join(dir, fileName), data, 'utf8', (err) => {
            if (err) {
                reject(err);
            } else {
                resolve(data);
            }
        });
    });
}

function createScriptSection(script, description) {
    return `// Script section${description ? ` ${description}` : ''}

{
${script.replace(/^(?!(\n|\r|$))/gm, '    ').trimEnd()}
}

`;
}

function createRuleSection(rule, description) {
    return `// Rule section${description ? ` ${description}` : ''}

${rule}

`;
}

function createHeaderSection() {
    return `//
// Generated by build-pegjs utility v.0.0.1
//

`;
}

module.exports = {
    readFile,
    writeFile,
    createScriptSection,
    createRuleSection,
    createHeaderSection,
};
