export const EActorName = <const>{
    Root: 'Root',
    Metrics: 'Metrics',
    Settings: 'Settings',
    Handlers: 'Handlers',
    Dictionaries: 'Dictionaries',
    SnapshotsAndHistory: 'SnapshotsAndHistory',
    ChartsDataProvider: 'BacktestingDataProviders',
    BacktestingDataProviders: 'BacktestingDataProviders',
    PortfolioTrackerHandlers: 'PortfolioTrackerHandlers',
    HerodotusTasks: 'HerodotusTasks',
    Heartbeat: 'Heartbeat',

    SettingsTab: `SettingsTab`,
    DashboardTab: `DashboardTab`,
    BacktestingTab: `BacktestingTab`,
    TradingStatsTab: `TradingStatsTab`,
    HerodotusTradesTab: `HerodotusTradesTab`,
    PortfolioTrackerTab: `PortfolioTrackerTab`,
    HerodotusTerminalTab: `HerodotusTerminalTab`,
    HerodotusDashboardTab: `HerodotusDashboardTab`,
    TradingServerManagerTab: `TradingServerManagerTab`,
    CharterDebuggerTab: `CharterDebuggerTab`,
    CharterJsonViewerTab: `CharterJsonViewerTab`,
    BalanceMonitorTab: `BalanceMonitorTab`,
    WSQueryTerminal: `WSQueryTerminal`,

    DashboardsStorage: 'DashboardsStorage',
    FullDashboards: 'FullDashboards',
};
