export const EActorName = <const>{
    Root: 'Root',
    Metrics: 'Metrics',
    Settings: 'Settings',
    Handlers: 'Handlers',
    Keycloak: 'Keycloak',
    Session: 'Session',
    Dictionaries: 'Dictionaries',
    InfinityHistory: 'InfinityHistory',
    AuthzDataProvider: 'AuthzDataProvider',
    ChartsDataProvider: 'ChartsDataProvider',
    IndicatorsDataProvider: 'IndicatorsDataProvider',
    ComponentsDataProvider: 'ComponentsDataProvider',
    BacktestingDataProvider: 'BacktestingDataProvider',
    TradingServersManagerDataProvider: 'TradingServersManagerDataProvider',
    HerodotusTasks: 'HerodotusTasks',
    Heartbeat: 'Heartbeat',

    AuthzTab: 'AuthzTab',
    SettingsTab: `SettingsTab`,
    DashboardTab: `DashboardTab`,
    BacktestingTab: `BacktestingTab`,
    TradingStatsTab: `TradingStatsTab`,
    HerodotusTradesTab: `HerodotusTradesTab`,
    HerodotusTerminalTab: `HerodotusTerminalTab`,
    HerodotusDashboardTab: `HerodotusDashboardTab`,
    TradingServerManagerTab: `TradingServerManagerTab`,
    CharterDebuggerTab: `CharterDebuggerTab`,
    CharterJsonViewerTab: `CharterJsonViewerTab`,
    BalanceMonitorTab: `BalanceMonitorTab`,
    WSQueryTerminal: `WSQueryTerminal`,
    IndexTab: `IndexTab`,

    DashboardsStorage: 'DashboardsStorage',
    FullDashboards: 'FullDashboards',
};
